//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course
    {
        public Course()
        {
            this.Students = new HashSet<Student>();
        }
    
        [Display(Name="Código")]
        public int Code { get; set; }
        [Display(Name = "Assunto")]
        public string SubjectCode { get; set; }
        [Display(Name = "Data Início")]
        public System.DateTime StartDate { get; set; }
        [Display(Name = "Data Término")]
        public Nullable<System.DateTime> EndDate { get; set; }
        [Display(Name = "Horário")]
        public string Timing { get; set; }
        [Display(Name = "Valor")]
        public Nullable<int> CourseFee { get; set; }
        [Display(Name = "Obs.")]
        public string Remarks { get; set; }
        [Display(Name = "Nome")]
        public string CourseName { get; set; }
    
        public virtual Subject Subjects { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
