//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        [Display(Name = "Código")]
        public int Id { get; set; }
        [Display(Name = "Código do Curso")]
        public Nullable<int> CourseCode { get; set; }
        [Display(Name = "No. Inscrição")]
        public int RollNo { get; set; }
        [Display(Name = "Nome")]
        public string Fullname { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "Celular")]
        public string Mobile { get; set; }
        [Display(Name = "Ocupação")]
        public string Occupation { get; set; }
        [Display(Name = "Qualificação")]
        public string Qualification { get; set; }
        [Display(Name = "Matriculado em")]
        public Nullable<System.DateTime> JoinedOn { get; set; }
        [Display(Name = "Valor Pago")]
        public Nullable<int> FeePaid { get; set; }
        [Display(Name = "Obs.")]
        public string Remarks { get; set; }
    
        public virtual Course Courses { get; set; }
    }
}
