//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Courses = new HashSet<Course>();
        }

        [Display(Name = "Código")]
        public string Code { get; set; }
        [Display(Name = "Titulo")]
        public string Title { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
